#!/usr/bin/env ruby

# @todo move to reap proper
#require 'facets/string/file'
#require 'facets/kernel/ask'  # TODO: make sure reap provides this

#
# TODO: Do things in ruby instead of shelling out!
#

metadata = YAML.load_file('.ruby')
version  = metadata['version']

desc 'update manifest file'
task 'manifest' do
  system 'mast -u'
end

desc 'release and tag'
task 'release' do
  exit -1 unless system('detroit release')
  system "pom news | git tag -a -F - #{version}"
end

file 'var/*' do
  system 'dotruby source var'
end

#file 'Profile' do
#  system 'dotruby source Profile'
#end

file 'lib/**/*' do
  exit -1 unless system('detroit test')
end


#require 'facets/functor'
#class String
#  def file
#    str = self
#    Functor.new do |op,*a,&b|
#      FileUtils.send(op,str,*a,&b)
#    end
#  end
#end
